### PR TITLE
remove Build.PL and update Makefile.PL

### PR DESCRIPTION
**Pull request by haarg**
Providing both Build.PL and Makefile.PL is redundant and makes it easy
for metadata to be inconsistent.

Remove Build.PL, as it requires Module::Build, which is has been removed
from core.

Update Makefile.PL to include HTML::Selector::XPath as a recommended
prereq.

### CODE REVIEW

**Comment by haarg** [comment]
@manwar Any chance of getting this merged/released?

**Comment by manwar** [comment]
> @manwar Any chance of getting this merged/released?

Sorry for late action. I will get it done later in the evening.

**Comment by manwar** [comment]
Thanks @haarg

**Comment by manwar** [comment]
@haarg Test::XPath v0,20 released.

https://metacpan.org/release/MANWAR/Test-XPath-0.20

**Pull request merged**
